name: Build and Release ClipboardInspector

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build self-contained single-file EXE
        run: dotnet publish ClipboardInspector/ClipboardInspector.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:EnableCompressionInSingleFile=true -p:DebugType=none --output publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: clipboard-inspector
          path: publish/ClipboardInspector.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: publish/ClipboardInspector.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # ← oder dein personal token, falls nötig
